export const ProductList = [
  {
    id: 1,
    image: "tier1.png",
    name: "Starter Server S-1",
    price: "5€",
    ram: "2 GB Ram",
    cpu: "2 Core Cpu",
    disk: "20 GB SSD",
    location: "TR/İstanbul",
  },
  {
    id: 2,
    image: "tier1.png",
    name: "Starter Server S-2",
    price: "8€",
    ram: "4 GB Ram",
    cpu: "2 Core Cpu",
    disk: "30 GB SSD",
    location: "TR/İstanbul",
  },
  {
    id: 3,
    image: "tier1.png",
    name: "Starter Server S-3",
    price: "10€",
    ram: "6 GB Ram",
    cpu: "2 Core Cpu",
    disk: "40 GB SSD",
    location: "TR/İstanbul",
  },
  {
    id: 4,
    image: "tier2.png",
    name: "Mid Level Server E-1",
    price: "20€",
    ram: "8 GB Ram",
    cpu: "4 Core Cpu",
    disk: "75 GB SSD",
    location: "TR/İstanbul",
  },
  {
    id: 5,
    image: "tier2.png",
    name: "Mid Level Server E-2",
    price: "35€",
    ram: "12 GB Ram",
    cpu: "4 Core Cpu",
    disk: "100 GB SSD",
    location: "TR/İstanbul",
  },
  {
    id: 6,
    image: "tier2.png",
    name: "Mid Level Server E-3",
    price: "50€",
    ram: "16 GB Ram",
    cpu: "4 Core Cpu",
    disk: "200 GB SSD",
    location: "TR/İstanbul",
  },
  {
    id: 7,
    image: "tier3.png",
    name: "Professional Server O-1",
    price: "100€",
    ram: "32 GB Ram",
    cpu: "8 Core Cpu",
    disk: "250 GB SSD",
    location: "TR/Bursa",
  },
  {
    id: 8,
    image: "tier3.png",
    name: "Professional Server O-2",
    price: "250€",
    ram: "64 GB Ram",
    cpu: "12 Core Cpu",
    disk: "500 GB SSD",
    location: "TR/Bursa",
  },
  {
    id: 9,
    image: "tier3.png",
    name: "Professional Server O-3",
    price: "500€",
    ram: "128 GB Ram",
    cpu: "16 Core Cpu",
    disk: "İnfinity SSD",
    location: "TR/Bursa",
  },
];
